# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{redmine_rate}
  s.version = "0.2.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Eric Davis"]
  s.date = %q{2011-04-28}
  s.description = %q{The Rate plugin stores billing rates for Users.  It also provides an API that can be used to find the rate for a Member of a Project at a specific date.}
  s.email = %q{edavis@littlestreamsoftware.com}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "COPYRIGHT.txt",
     "CREDITS.txt",
     "GPL.txt",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "app/controllers/rate_caches_controller.rb",
     "app/controllers/rates_controller.rb",
     "app/models/rate.rb",
     "app/views/rate_caches/index.html.erb",
     "app/views/rates/_form.html.erb",
     "app/views/rates/_list.html.erb",
     "app/views/rates/create.js.rjs",
     "app/views/rates/create_error.js.rjs",
     "app/views/rates/edit.html.erb",
     "app/views/rates/index.html.erb",
     "app/views/rates/new.html.erb",
     "app/views/rates/show.html.erb",
     "app/views/users/_membership_rate.html.erb",
     "app/views/users/_rates.html.erb",
     "assets/images/database_refresh.png",
     "config/locales/de.yml",
     "config/locales/en.yml",
     "config/locales/fr.yml",
     "config/locales/ru.yml",
     "config/routes.rb",
     "init.rb",
     "lang/de.yml",
     "lang/en.yml",
     "lang/fr.yml",
     "lib/rate_conversion.rb",
     "lib/rate_memberships_hook.rb",
     "lib/rate_project_hook.rb",
     "lib/rate_sort_helper_patch.rb",
     "lib/rate_time_entry_patch.rb",
     "lib/rate_users_helper_patch.rb",
     "lib/redmine_rate/hooks/plugin_timesheet_view_timesheets_report_header_tags_hook.rb",
     "lib/redmine_rate/hooks/plugin_timesheet_views_timesheet_group_header_hook.rb",
     "lib/redmine_rate/hooks/plugin_timesheet_views_timesheet_time_entry_hook.rb",
     "lib/redmine_rate/hooks/plugin_timesheet_views_timesheet_time_entry_sum_hook.rb",
     "lib/redmine_rate/hooks/plugin_timesheet_views_timesheets_time_entry_row_class_hook.rb",
     "lib/redmine_rate/hooks/timesheet_hook_helper.rb",
     "lib/redmine_rate/hooks/view_layouts_base_html_head_hook.rb",
     "lib/tasks/cache.rake",
     "lib/tasks/data.rake",
     "rails/init.rb",
     "test/functional/rates_controller_test.rb",
     "test/integration/admin_panel_test.rb",
     "test/integration/routing_test.rb",
     "test/test_helper.rb",
     "test/unit/lib/rate_time_entry_patch_test.rb",
     "test/unit/lib/rate_users_helper_patch_test.rb",
     "test/unit/lib/redmine_rate/hooks/plugin_timesheet_view_timesheets_report_header_tags_hook_test.rb",
     "test/unit/lib/redmine_rate/hooks/plugin_timesheet_views_timesheet_group_header_hook_test.rb",
     "test/unit/lib/redmine_rate/hooks/plugin_timesheet_views_timesheet_time_entry_hook_test.rb",
     "test/unit/lib/redmine_rate/hooks/plugin_timesheet_views_timesheet_time_entry_sum_hook_test.rb",
     "test/unit/lib/redmine_rate/hooks/plugin_timesheet_views_timesheets_time_entry_row_class_hook_test.rb",
     "test/unit/rate_for_test.rb",
     "test/unit/rate_test.rb"
  ]
  s.homepage = %q{https://projects.littlestreamsoftware.com/projects/redmine-rate}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{A Rate plugin for Redmine to store billing rate for user.}
  s.test_files = [
    "test/test_helper.rb",
     "test/integration/routing_test.rb",
     "test/integration/admin_panel_test.rb",
     "test/unit/rate_for_test.rb",
     "test/unit/lib/rate_time_entry_patch_test.rb",
     "test/unit/lib/rate_users_helper_patch_test.rb",
     "test/unit/lib/redmine_rate/hooks/plugin_timesheet_views_timesheets_time_entry_row_class_hook_test.rb",
     "test/unit/lib/redmine_rate/hooks/plugin_timesheet_views_timesheet_time_entry_hook_test.rb",
     "test/unit/lib/redmine_rate/hooks/plugin_timesheet_views_timesheet_group_header_hook_test.rb",
     "test/unit/lib/redmine_rate/hooks/plugin_timesheet_views_timesheet_time_entry_sum_hook_test.rb",
     "test/unit/lib/redmine_rate/hooks/plugin_timesheet_view_timesheets_report_header_tags_hook_test.rb",
     "test/unit/rate_test.rb",
     "test/functional/rates_controller_test.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

