# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{redmine_rate}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Eric Davis"]
  s.date = %q{2009-10-13}
  s.description = %q{The Rate plugin stores billing rates for Users.  It also provides an API that can be used to find the rate for a Member of a Project at a specific date.}
  s.email = %q{edavis@littlestreamsoftware.com}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "COPYRIGHT.txt",
     "CREDITS.txt",
     "GPL.txt",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "app/controllers/rates_controller.rb",
     "app/models/rate.rb",
     "app/views/rates/_form.html.erb",
     "app/views/rates/_list.html.erb",
     "app/views/rates/create.js.rjs",
     "app/views/rates/create_error.js.rjs",
     "app/views/rates/edit.html.erb",
     "app/views/rates/index.html.erb",
     "app/views/rates/new.html.erb",
     "app/views/rates/show.html.erb",
     "app/views/users/_membership_rate.html.erb",
     "app/views/users/_rates.html.erb",
     "config/locales/en.yml",
     "config/routes.rb",
     "init.rb",
     "lang/en.yml",
     "lib/rate_conversion.rb",
     "lib/rate_memberships_hook.rb",
     "lib/rate_project_hook.rb",
     "lib/rate_sort_helper_patch.rb",
     "lib/rate_time_entry_patch.rb",
     "lib/rate_users_helper_patch.rb",
     "lib/tasks/data.rake",
     "rails/init.rb"
  ]
  s.homepage = %q{https://projects.littlestreamsoftware.com/projects/redmine-timesheet}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubyforge_project = %q{redmine_rate}
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{A Rate plugin for Redmine to store billing rate for user.}
  s.test_files = [
    "spec/lib/rate_users_helper_patch_spec.rb",
     "spec/lib/rate_time_entry_patch_spec.rb",
     "spec/spec_helper.rb",
     "spec/models/rate_for_spec.rb",
     "spec/models/rate_spec.rb",
     "spec/controllers/rates_routing_spec.rb",
     "spec/controllers/rates_controller_spec.rb",
     "spec/sanity_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end
